/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.Classes.Relatorios;

import br.com.Conexao.ConexaoPostgres;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lavanderia
 */
public class Relatório003 extends javax.swing.JFrame {

    /**
     * Creates new form Relatório003
     */
    public Relatório003() {
        initComponents();
        this.setLocationRelativeTo(null);
        configurarEPreencherComponentes();
    }

    private void configurarEPreencherComponentes() {
        // 1. Preenche o JComboBoxStatus com as opções solicitadas
        jComboBoxStatus.removeAllItems();
        jComboBoxStatus.addItem("ATIVO");
        jComboBoxStatus.addItem("DEMITIDO");
        jComboBoxStatus.addItem("EM PROCESSO");
        jComboBoxStatus.addItem("CANCELADO");
        jComboBoxStatus.addItem("AFASTADO");

        // 2. Carrega as empresas na tabela com a coluna Checkbox
        carregarEmpresas();
    }

    private void carregarEmpresas() {
        // Modelo de tabela customizado para aceitar Boolean (Checkbox) na primeira coluna
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[][]{},
                new String[]{"Selecionar", "ID", "Empresa"} // ID continua aqui internamente
        ) {
            Class[] types = new Class[]{
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                true, false, false // Apenas a coluna do Checkbox pode ser editada
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        jTableEmpresa.setModel(modelo);

        // --- TRUQUE PARA OCULTAR A COLUNA DO ID ---
        // Removemos a coluna ID (índice 1) da visualização da tabela, mas ela continua existindo no Modelo (dados)
        jTableEmpresa.getColumnModel().removeColumn(jTableEmpresa.getColumnModel().getColumn(1));

        // Ajusta a largura das colunas visíveis restantes
        jTableEmpresa.getColumnModel().getColumn(0).setPreferredWidth(80);  // Checkbox
        jTableEmpresa.getColumnModel().getColumn(1).setPreferredWidth(300); // Nome Fantasia (agora índice 1 visualmente)

        String sql = "SELECT \"ID_EMPRESA\", \"NOME_FANTASIA\" FROM \"Empresa\" ORDER BY \"NOME_FANTASIA\" ASC";
        

        try ( Connection conn = ConexaoPostgres.conectar();  PreparedStatement pst = conn.prepareStatement(sql);  ResultSet rs = pst.executeQuery()) {

            while (rs.next()) {
                int id = rs.getInt("ID_EMPRESA");
                String nomeFantasia = rs.getString("NOME_FANTASIA");

                // Adiciona a linha normalmente: Checkbox desmarcado, ID, e o Nome da Empresa
                modelo.addRow(new Object[]{Boolean.FALSE, id, nomeFantasia});
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao carregar empresas:\n" + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpresa = new javax.swing.JTable();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jButtonGerar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relatório Funcionários por Empresas");

        jTableEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableEmpresa);

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonGerar.setText("Gerar");
        jButtonGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarActionPerformed(evt);
            }
        });

        jLabel1.setText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jButtonGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarActionPerformed
        // 1. Obter o Status selecionado no ComboBox
        String statusSelecionado = (String) jComboBoxStatus.getSelectedItem();

        // 2. Obter a lista de IDs das empresas marcadas na JTable
        java.util.List<Integer> idsEmpresasMarcadas = new java.util.ArrayList<>();
        DefaultTableModel modelo = (DefaultTableModel) jTableEmpresa.getModel();

        for (int i = 0; i < modelo.getRowCount(); i++) {
            Boolean marcado = (Boolean) modelo.getValueAt(i, 0); // Coluna do Checkbox
            if (marcado != null && marcado) {
                // Buscamos o ID diretamente da coluna 1 (que está oculta na tela mas existe no modelo)
                int idEmpresa = (int) modelo.getValueAt(i, 1);
                idsEmpresasMarcadas.add(idEmpresa);
            }
        }

        // Validação: Se nenhuma empresa foi selecionada
        if (idsEmpresasMarcadas.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, selecione ao menos uma empresa na tabela para gerar o relatório.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 3. Definir o diretório padrão onde os relatórios serão salvos
            String caminhoDiretorio = "F:\\Lavanderia\\Backup\\Relatorios";
            java.io.File pasta = new java.io.File(caminhoDiretorio);

            // Se a pasta não existir no computador, cria ela automaticamente (incluindo subpastas se necessário)
            if (!pasta.exists()) {
                pasta.mkdirs();
            }

            // 4. Gerar a data e hora formatadas para o nome do arquivo
            // Exemplo final: Relat_Func_Empresas-17-07-085622.pdf (Substituímos / por - para ser válido no Windows)
            java.text.SimpleDateFormat formatadorNome = new java.text.SimpleDateFormat("dd-MM-HHmmss");
            String dataHoraFormatada = formatadorNome.format(new java.util.Date());

            // Se você quiser o formato exato com barra como texto (ex: 17_07 para imitar a data):
            java.text.SimpleDateFormat formatadorData = new java.text.SimpleDateFormat("dd_MM");
            java.text.SimpleDateFormat formatadorHora = new java.text.SimpleDateFormat("HHmmss");
            String nomeArquivo = "Relat_Func_Empresas-" + formatadorData.format(new java.util.Date()) + "-" + formatadorHora.format(new java.util.Date()) + ".pdf";

            // Monta o caminho completo final
            String caminhoCompleto = caminhoDiretorio + java.io.File.separator + nomeArquivo;

            // 5. Chamar o método que gera o PDF passando os filtros e o caminho gerado automaticamente
            gerarRelatorioPDF(caminhoCompleto, statusSelecionado, idsEmpresasMarcadas);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Erro ao preparar o caminho de salvamento do arquivo:\n" + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonGerarActionPerformed

private void gerarRelatorioPDF(String caminhoDestino, String statusFiltro, java.util.List<Integer> idsEmpresas) {
        // Criação do documento A4
        com.lowagie.text.Document documento = new com.lowagie.text.Document(com.lowagie.text.PageSize.A4);

        try {
            com.lowagie.text.pdf.PdfWriter.getInstance(documento, new java.io.FileOutputStream(caminhoDestino));
            documento.open();

            // --- 1. CONFIGURAÇÃO DA PALETA MONOCROMÁTICA (PRETO / CINZA) ---
            java.awt.Color pretoPuro = java.awt.Color.BLACK;
            java.awt.Color cinzaEscuroGrafite = new java.awt.Color(74, 85, 104);  // #4A5568 - Excelente para cabeçalhos de tabelas
            java.awt.Color cinzaTextoMuted = new java.awt.Color(113, 128, 150);  // #718096 - Para subtítulos e datas
            java.awt.Color cinzaBorda = new java.awt.Color(204, 214, 224);       // #CCD6E0 - Linhas de grade sutis
            java.awt.Color cinzaFundoZebra = new java.awt.Color(247, 250, 252);   // #F7FAFC - Fundo zebrado bem suave
            java.awt.Color brancoPuro = java.awt.Color.WHITE;

            // --- 2. CONFIGURAÇÃO DE FONTES ---
            com.lowagie.text.Font fonteTitulo = com.lowagie.text.FontFactory.getFont(com.lowagie.text.FontFactory.HELVETICA_BOLD, 18, pretoPuro);
            com.lowagie.text.Font fonteSubtitulo = com.lowagie.text.FontFactory.getFont(com.lowagie.text.FontFactory.HELVETICA, 10, cinzaTextoMuted);
            com.lowagie.text.Font landmarkFont = com.lowagie.text.FontFactory.getFont(com.lowagie.text.FontFactory.HELVETICA_BOLD, 12, pretoPuro);
            com.lowagie.text.Font fonteCabecalhoTabela = com.lowagie.text.FontFactory.getFont(com.lowagie.text.FontFactory.HELVETICA_BOLD, 9, brancoPuro);
            com.lowagie.text.Font fonteLinhaTabela = com.lowagie.text.FontFactory.getFont(com.lowagie.text.FontFactory.HELVETICA, 9, pretoPuro);
            com.lowagie.text.Font fonteFiltroNegrito = com.lowagie.text.FontFactory.getFont(com.lowagie.text.FontFactory.HELVETICA_BOLD, 9, pretoPuro);
            com.lowagie.text.Font fonteTotal = com.lowagie.text.FontFactory.getFont(com.lowagie.text.FontFactory.HELVETICA_BOLD, 9, pretoPuro);

            // --- 3. CABEÇALHO DO RELATÓRIO ---
            com.lowagie.text.Paragraph titulo = new com.lowagie.text.Paragraph("FUNCIONÁRIOS POR EMPRESA", fonteTitulo);
            titulo.setAlignment(com.lowagie.text.Element.ALIGN_LEFT);
            documento.add(titulo);

            com.lowagie.text.Paragraph subtitulo = new com.lowagie.text.Paragraph("Projeto RH - Relatório Administrativo Operacional", fonteSubtitulo);
            subtitulo.setSpacingAfter(15);
            documento.add(subtitulo);

            // Linha divisória preta/cinza escura decorativa do cabeçalho geral
            com.lowagie.text.pdf.draw.LineSeparator linhaDivisoriaGeral = new com.lowagie.text.pdf.draw.LineSeparator();
            linhaDivisoriaGeral.setLineColor(cinzaEscuroGrafite);
            linhaDivisoriaGeral.setPercentage(100);
            linhaDivisoriaGeral.setOffset(-5);
            documento.add(linhaDivisoriaGeral);

            // --- 4. METADADOS E FILTROS NO TOPO ---
            com.lowagie.text.Paragraph metadados = new com.lowagie.text.Paragraph();
            metadados.setSpacingBefore(10);
            metadados.setSpacingAfter(20);
            metadados.add(new com.lowagie.text.Chunk("Filtro por Status: ", fonteSubtitulo));
            metadados.add(new com.lowagie.text.Chunk(statusFiltro + "       ", fonteFiltroNegrito));

            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm");
            metadados.add(new com.lowagie.text.Chunk("Gerado em: " + sdf.format(new java.util.Date()), fonteSubtitulo));
            documento.add(metadados);

            // --- 5. CONSULTA AO BANCO DE DADOS POSTGRES ---
            StringBuilder interrogacoes = new StringBuilder();
            for (int i = 0; i < idsEmpresas.size(); i++) {
                interrogacoes.append("?");
                if (i < idsEmpresas.size() - 1) {
                    interrogacoes.append(",");
                }
            }

            String sql = "SELECT e.\"NOME_FANTASIA\" AS empresa_nome, f.\"NOME\", f.\"SETOR\", f.\"STATUS\" "
                    + "FROM \"Funcionarios\" f "
                    + "INNER JOIN \"Empresa\" e ON f.\"EMPRESA\" = e.\"NOME_FANTASIA\" "
                    + "WHERE f.\"STATUS\" = ? AND e.\"ID_EMPRESA\" IN (" + interrogacoes.toString() + ") "
                    + "ORDER BY e.\"NOME_FANTASIA\" ASC, f.\"SETOR\", f.\"NOME\" ASC";

            try ( Connection conn = ConexaoPostgres.conectar();  PreparedStatement pst = conn.prepareStatement(sql)) {

                pst.setString(1, statusFiltro);

                for (int i = 0; i < idsEmpresas.size(); i++) {
                    pst.setInt(i + 2, idsEmpresas.get(i));
                }

                try ( ResultSet rs = pst.executeQuery()) {
                    
                    String empresaAtual = "";
                    com.lowagie.text.pdf.PdfPTable tabela = null;
                    int totalFuncionariosEmpresa = 0;
                    boolean zebra = false;
                    int totalGeralRegistros = 0;

                    while (rs.next()) {
                        totalGeralRegistros++;
                        String empresaRow = rs.getString("empresa_nome");
                        String nome = rs.getString("NOME");
                        String setor = rs.getString("SETOR");
                        String status = rs.getString("STATUS");

                        // Controle de quebra e agrupamento por empresa
                        if (!empresaRow.equals(empresaAtual)) {
                            
                            // Se já havia uma tabela rodando, adiciona totais e renderiza antes da próxima empresa
                            if (tabela != null) {
                                adicionarLinhaTotal(tabela, totalFuncionariosEmpresa, fonteTotal, cinzaEscuroGrafite);
                                documento.add(tabela);
                                
                                // Pula rigorosamente as 3 linhas pedidas
                                com.lowagie.text.Paragraph espacamento = new com.lowagie.text.Paragraph("\n\n\n");
                                espacamento.setLeading(10.0f);
                                documento.add(espacamento);
                            }

                            // Reinicia contadores locais da nova empresa
                            empresaAtual = empresaRow;
                            totalFuncionariosEmpresa = 0;
                            zebra = false;

                            // Escreve o título da Empresa em PRETO Puro
                            com.lowagie.text.Paragraph tituloEmpresa = new com.lowagie.text.Paragraph("EMPRESA: " + empresaAtual.toUpperCase(), landmarkFont);
                            tituloEmpresa.setSpacingBefore(10);
                            tituloEmpresa.setSpacingAfter(8);
                            documento.add(tituloEmpresa);

                            // Inicializa tabela: Estrutura limpa de 3 colunas
                            tabela = new com.lowagie.text.pdf.PdfPTable(new float[]{5.0f, 3.0f, 2.0f});
                            tabela.setWidthPercentage(100);

                            // Cabeçalhos da tabela em Cinza Grafite Escuro com Letras Brancas (Contraste perfeito)
                            String[] cabecalhos = {"Nome do Funcionário", "Setor", "Status"};
                            for (String c : cabecalhos) {
                                com.lowagie.text.pdf.PdfPCell celulaCabecalho = new com.lowagie.text.pdf.PdfPCell(new com.lowagie.text.Paragraph(c, fonteCabecalhoTabela));
                                celulaCabecalho.setBackgroundColor(cinzaEscuroGrafite);
                                celulaCabecalho.setPadding(6);
                                celulaCabecalho.setHorizontalAlignment(com.lowagie.text.Element.ALIGN_LEFT);
                                tabela.addCell(celulaCabecalho);
                            }
                        }

                        totalFuncionariosEmpresa++;

                        // Montagem das células de dados
                        com.lowagie.text.pdf.PdfPCell cNome = new com.lowagie.text.pdf.PdfPCell(new com.lowagie.text.Paragraph(nome, fonteLinhaTabela));
                        com.lowagie.text.pdf.PdfPCell cSetor = new com.lowagie.text.pdf.PdfPCell(new com.lowagie.text.Paragraph(setor, fonteLinhaTabela));
                        com.lowagie.text.pdf.PdfPCell cStatus = new com.lowagie.text.pdf.PdfPCell(new com.lowagie.text.Paragraph(status, fonteLinhaTabela));

                        com.lowagie.text.pdf.PdfPCell[] linha = {cNome, cSetor, cStatus};
                        for (com.lowagie.text.pdf.PdfPCell cel : linha) {
                            cel.setPadding(5);
                            cel.setBorderColor(cinzaBorda);
                            if (zebra) {
                                cel.setBackgroundColor(cinzaFundoZebra); // Aplica o fundo cinza claro na linha zebrada
                            }
                        }

                        tabela.addCell(cNome);
                        tabela.addCell(cSetor);
                        tabela.addCell(cStatus);

                        zebra = !zebra;
                    }

                    // Insere a última empresa ao sair do laço
                    if (tabela != null) {
                        adicionarLinhaTotal(tabela, totalFuncionariosEmpresa, fonteTotal, cinzaEscuroGrafite);
                        documento.add(tabela);
                    }

                    // Validação de segurança para tabelas sem dados retornados
                    if (totalGeralRegistros == 0) {
                        com.lowagie.text.pdf.PdfPTable tabelaVazia = new com.lowagie.text.pdf.PdfPTable(1);
                        tabelaVazia.setWidthPercentage(100);
                        com.lowagie.text.pdf.PdfPCell celulaVazia = new com.lowagie.text.pdf.PdfPCell(new com.lowagie.text.Paragraph("Nenhum funcionário encontrado sob estes critérios.", fonteLinhaTabela));
                        celulaVazia.setPadding(12);
                        celulaVazia.setHorizontalAlignment(com.lowagie.text.Element.ALIGN_CENTER);
                        tabelaVazia.addCell(celulaVazia);
                        documento.add(tabelaVazia);
                    }
                }

            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro de banco de dados ao processar relatório:\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            JOptionPane.showMessageDialog(this, "Relatório gerado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            abrirPDFDoSistema(caminhoDestino);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao gerar PDF:\n" + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (documento.isOpen()) {
                documento.close();
            }
        }
    }

    // Método auxiliar adaptado para o fechamento com traço em cinza escuro nítido
    private void adicionarLinhaTotal(com.lowagie.text.pdf.PdfPTable tabela, int total, com.lowagie.text.Font fonteTotal, java.awt.Color corLinha) {
        // Linha divisória horizontal sólida abaixo da última linha de dados
        com.lowagie.text.pdf.PdfPCell divisoria = new com.lowagie.text.pdf.PdfPCell();
        divisoria.setColspan(3);
        divisoria.setFixedHeight(1.2f);
        divisoria.setBorder(com.lowagie.text.Rectangle.TOP);
        divisoria.setBorderColor(corLinha); 
        tabela.addCell(divisoria);

        // Texto do Total
        com.lowagie.text.pdf.PdfPCell cTextoTotal = new com.lowagie.text.pdf.PdfPCell(new com.lowagie.text.Paragraph("Total de Funcionários Listados:", fonteTotal));
        cTextoTotal.setColspan(2);
        cTextoTotal.setPadding(6);
        cTextoTotal.setBorder(com.lowagie.text.Rectangle.NO_BORDER);
        cTextoTotal.setHorizontalAlignment(com.lowagie.text.Element.ALIGN_RIGHT);

        // Valor numérico totalizado
        com.lowagie.text.pdf.PdfPCell cNumeroTotal = new com.lowagie.text.pdf.PdfPCell(new com.lowagie.text.Paragraph(String.valueOf(total), fonteTotal));
        cNumeroTotal.setPadding(6);
        cNumeroTotal.setBorder(com.lowagie.text.Rectangle.NO_BORDER);
        cNumeroTotal.setHorizontalAlignment(com.lowagie.text.Element.ALIGN_LEFT);

        tabela.addCell(cTextoTotal);
        tabela.addCell(cNumeroTotal);
    }

    
    // Método auxiliar seguro para abrir o PDF no leitor padrão do Windows
    private void abrirPDFDoSistema(String caminhoDestino) {
    // Usamos uma Thread separada para que o processo do PDF não concorra com a interface do Java
    new Thread(() -> {
        try {
            java.io.File arquivo = new java.io.File(caminhoDestino);
            
            if (arquivo.exists()) {
                // Verifica se o Desktop é suportado pelo Sistema Operacional (Windows/Linux/Mac)
                if (java.awt.Desktop.isDesktopSupported()) {
                    java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
                    
                    // Abre o arquivo de forma assíncrona e independente
                    desktop.open(arquivo);
                } else {
                    // Alternativa caso o Desktop do Java falhe por limitação do SO
                    Runtime.getRuntime().exec("cmd /c start \"\" \"" + caminhoDestino + "\"");
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            System.err.println("Não foi possível abrir o PDF automaticamente: " + ex.getMessage());
        }
    }).start();
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatório003.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatório003.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatório003.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatório003.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatório003().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGerar;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpresa;
    // End of variables declaration//GEN-END:variables
}
