/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.Visao;

/**
 *
 * @author Lavanderia
 */
public class TelaAfastamento extends javax.swing.JFrame {

    private int idFuncionario;

    private Integer idAfastamentoSelecionado = null;

    /**
     * Creates new form TelaAfastamento
     */
    public TelaAfastamento() {

    }

    public TelaAfastamento(int idFuncionario, String nomeFuncionario) {

        initComponents();
        setLocationRelativeTo(null);
        this.idFuncionario = idFuncionario;

        jTextFieldIDFuncionario.setText(String.valueOf(idFuncionario));

        jTextFieldIDFuncionario.setEditable(false);

        setTitle("Afastamentos - " + nomeFuncionario);

        carregarTabelaAfastamentos();

    }

    private void carregarTabelaAfastamentos() {

        try ( java.sql.Connection conn
                = br.com.Conexao.ConexaoPostgres.conectar()) {

            String sql = """
                     SELECT "ID",
                            "DATA_AFASTAMENTO",
                            "DATA_RETORNO",
                            "MOTIVO"
                     FROM "Afastados"
                     WHERE "ID_FUNC" = ?
                     ORDER BY "DATA_AFASTAMENTO" DESC
                     """;

            java.sql.PreparedStatement ps
                    = conn.prepareStatement(sql);

            ps.setInt(1, idFuncionario);

            java.sql.ResultSet rs = ps.executeQuery();

            // Sobrescrevemos o DefaultTableModel para retornar false em todas as células
            javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
                    new Object[]{
                        "ID",
                        "DATA AFASTAMENTO",
                        "DATA RETORNO",
                        "MOTIVO"
                    }, 0
            ) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // Nenhuma célula poderá ser editada diretamente na tabela
                }
            };

            java.text.SimpleDateFormat sdf
                    = new java.text.SimpleDateFormat("dd/MM/yyyy");

            while (rs.next()) {

                java.sql.Date dataAfast
                        = rs.getDate("DATA_AFASTAMENTO");

                java.sql.Date dataRet
                        = rs.getDate("DATA_RETORNO");

                modelo.addRow(new Object[]{
                    rs.getInt("ID"),
                    dataAfast != null
                    ? sdf.format(dataAfast)
                    : "",
                    dataRet != null
                    ? sdf.format(dataRet)
                    : "",
                    rs.getString("MOTIVO")

                });

            }

            jTableMotivoAfastamento.setModel(modelo);
            ajustarColunasTabela();

        } catch (Exception e) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Erro ao carregar afastamentos:\n" + e.getMessage()
            );

        }

    }

    private void ajustarColunasTabela() {

        jTableMotivoAfastamento.setAutoResizeMode(
                javax.swing.JTable.AUTO_RESIZE_OFF
        );

        jTableMotivoAfastamento.getColumnModel()
                .getColumn(0).setPreferredWidth(30); // ID

        jTableMotivoAfastamento.getColumnModel()
                .getColumn(1).setPreferredWidth(120); // DATA AFASTAMENTO

        jTableMotivoAfastamento.getColumnModel()
                .getColumn(2).setPreferredWidth(120); // DATA RETORNO

        jTableMotivoAfastamento.getColumnModel()
                .getColumn(3).setPreferredWidth(280); // MOTIVO

    }

    private void limparCampos() {

        jDateChooserAfastamento.setDate(null);

        jDateChooserRetorno.setDate(null);

        jTextPaneMotivo.setText("");

    }

    private void atualizarEstadoCampos() {
        boolean editavel = !jRadioExcluir.isSelected();

        // Habilita ou desabilita os campos de edição
        jDateChooserAfastamento.setEnabled(editavel);
        jDateChooserRetorno.setEnabled(editavel);
        jTextPaneMotivo.setEnabled(editavel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonNovo = new javax.swing.JRadioButton();
        jRadioEditar = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMotivoAfastamento = new javax.swing.JTable();
        jTextFieldIDFuncionario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jDateChooserAfastamento = new com.toedter.calendar.JDateChooser();
        jDateChooserRetorno = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneMotivo = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jRadioExcluir = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jRadioButtonNovo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonNovo.setText("Novo");
        jRadioButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNovoActionPerformed(evt);
            }
        });

        jRadioEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioEditar.setText("Editar");
        jRadioEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEditarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jTableMotivoAfastamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMotivoAfastamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMotivoAfastamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMotivoAfastamento);

        jTextFieldIDFuncionario.setEnabled(false);

        jLabel2.setText("Data Afastamento");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jLabel3.setText("Motivo do Afastamento");

        jScrollPane2.setViewportView(jTextPaneMotivo);

        jLabel4.setText("Data Retorno");

        jRadioExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioExcluir.setText("Excluir");
        jRadioExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldIDFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooserAfastamento, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jDateChooserRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonNovo)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioEditar)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonNovo)
                            .addComponent(jRadioEditar)
                            .addComponent(jRadioExcluir)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIDFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserAfastamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNovoActionPerformed
        jRadioEditar.setSelected(false);
        jRadioExcluir.setSelected(false);
        limparCampos();
        idAfastamentoSelecionado = null;
        atualizarEstadoCampos();
        jDateChooserAfastamento.requestFocus();
    }//GEN-LAST:event_jRadioButtonNovoActionPerformed

    private void jRadioEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEditarActionPerformed
        jRadioButtonNovo.setSelected(false);
        jRadioExcluir.setSelected(false);
        limparCampos();
        idAfastamentoSelecionado = null;
        atualizarEstadoCampos();
    }//GEN-LAST:event_jRadioEditarActionPerformed

    private void jTableMotivoAfastamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMotivoAfastamentoMouseClicked
        int linha = jTableMotivoAfastamento.getSelectedRow();

        if (linha == -1) {
            return;
        }

        // Pega o ID da linha selecionada
        idAfastamentoSelecionado = (Integer) jTableMotivoAfastamento.getValueAt(linha, 0);

        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");

        // 1. Preenche Data de Afastamento
        try {
            Object valAfast = jTableMotivoAfastamento.getValueAt(linha, 1);
            if (valAfast != null && !valAfast.toString().trim().isEmpty()) {
                jDateChooserAfastamento.setDate(sdf.parse(valAfast.toString()));
            } else {
                jDateChooserAfastamento.setDate(null);
            }
        } catch (Exception e) {
            jDateChooserAfastamento.setDate(null);
        }

        // 2. Preenche Data de Retorno (CORRIGIDO)
        try {
            Object valRetorno = jTableMotivoAfastamento.getValueAt(linha, 2);
            if (valRetorno != null && !valRetorno.toString().trim().isEmpty()) {
                // Se a string NÃO estiver vazia, faz o parse para a Date do JDateChooser
                jDateChooserRetorno.setDate(sdf.parse(valRetorno.toString()));
            } else {
                // Se estiver vazia ou null, define como null
                jDateChooserRetorno.setDate(null);
            }
        } catch (Exception e) {
            jDateChooserRetorno.setDate(null);
        }

        // 3. Preenche Motivo
        Object motivoObj = jTableMotivoAfastamento.getValueAt(linha, 3);
        jTextPaneMotivo.setText(motivoObj != null ? motivoObj.toString() : "");


    }//GEN-LAST:event_jTableMotivoAfastamentoMouseClicked

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // --- LÓGICA DE EXCLUSÃO ---
        if (jRadioExcluir.isSelected()) {

            if (idAfastamentoSelecionado == null) {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Selecione um afastamento na tabela para excluir.",
                        "Atenção",
                        javax.swing.JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            int opcao = javax.swing.JOptionPane.showConfirmDialog(
                    this,
                    "Confirma exclusão do afastamento selecionado?",
                    "Confirmar Exclusão",
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.QUESTION_MESSAGE
            );

            if (opcao == javax.swing.JOptionPane.YES_OPTION) {

                String sql = """
                         DELETE FROM "Afastados"
                         WHERE "ID" = ?
                         """;

                try ( java.sql.Connection conn = br.com.Conexao.ConexaoPostgres.conectar();  java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {

                    ps.setInt(1, idAfastamentoSelecionado);
                    ps.executeUpdate();

                    javax.swing.JOptionPane.showMessageDialog(
                            this,
                            "Afastamento excluído com Sucesso!"
                    );

                    carregarTabelaAfastamentos();
                    limparCampos();
                    idAfastamentoSelecionado = null;

                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(
                            this,
                            "Erro ao excluir afastamento:\n" + e.getMessage(),
                            "Erro",
                            javax.swing.JOptionPane.ERROR_MESSAGE
                    );
                }
            }
            return; // Finaliza a execução para não cair nas validações de inserção/edição
        }

        // --- LÓGICA DE NOVO / EDITAR ---
        if (jDateChooserAfastamento.getDate() == null) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Informe a data de afastamento."
            );
            return;
        }

        java.sql.Date dataAfastamento = new java.sql.Date(
                jDateChooserAfastamento.getDate().getTime()
        );

        java.sql.Date dataRetorno = null;
        if (jDateChooserRetorno.getDate() != null) {
            dataRetorno = new java.sql.Date(jDateChooserRetorno.getDate().getTime());
        }

        String motivo = jTextPaneMotivo.getText();

        try ( java.sql.Connection conn = br.com.Conexao.ConexaoPostgres.conectar()) {

            if (jRadioButtonNovo.isSelected()) {

                String sql = """
                         INSERT INTO "Afastados"
                         ("ID_FUNC", "DATA_AFASTAMENTO", "DATA_RETORNO", "MOTIVO")
                         VALUES (?, ?, ?, ?)
                         """;

                java.sql.PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1, idFuncionario);
                ps.setDate(2, dataAfastamento);
                ps.setDate(3, dataRetorno);
                ps.setString(4, motivo);

                ps.executeUpdate();

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Afastamento registrado com sucesso."
                );

            } else if (jRadioEditar.isSelected()) {

                if (idAfastamentoSelecionado == null) {
                    javax.swing.JOptionPane.showMessageDialog(
                            this,
                            "Selecione um afastamento na tabela."
                    );
                    return;
                }

                String sql = """
                         UPDATE "Afastados"
                         SET "DATA_AFASTAMENTO" = ?,
                             "DATA_RETORNO" = ?,
                             "MOTIVO" = ?
                         WHERE "ID" = ?
                         """;

                java.sql.PreparedStatement ps = conn.prepareStatement(sql);
                ps.setDate(1, dataAfastamento);
                ps.setDate(2, dataRetorno);
                ps.setString(3, motivo);
                ps.setInt(4, idAfastamentoSelecionado);

                ps.executeUpdate();

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Afastamento atualizado com sucesso."
                );

            } else {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Selecione a opção 'Novo', 'Editar' ou 'Excluir'."
                );
                return;
            }

            carregarTabelaAfastamentos();
            limparCampos();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Erro ao salvar:\n" + e.getMessage()
            );
        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jRadioExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioExcluirActionPerformed
        jRadioButtonNovo.setSelected(false);
        jRadioEditar.setSelected(false);
        limparCampos();
        idAfastamentoSelecionado = null;
        atualizarEstadoCampos(); // Desabilita os campos

    }//GEN-LAST:event_jRadioExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAfastamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAfastamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAfastamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAfastamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAfastamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvar;
    private com.toedter.calendar.JDateChooser jDateChooserAfastamento;
    private com.toedter.calendar.JDateChooser jDateChooserRetorno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButtonNovo;
    private javax.swing.JRadioButton jRadioEditar;
    private javax.swing.JRadioButton jRadioExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMotivoAfastamento;
    private javax.swing.JTextField jTextFieldIDFuncionario;
    private javax.swing.JTextPane jTextPaneMotivo;
    // End of variables declaration//GEN-END:variables
}
