/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.Visao;

/**
 *
 * @author Lavanderia
 */
public class TelaCadFuncao extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadFuncao
     */
    public TelaCadFuncao() {
    initComponents();
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setLocationRelativeTo(null);
    
    // 🚀 Carrega os dados na JTable ao abrir a tela
    carregarTabelaFuncao();
    
    jTextFieldIDSetor.setEnabled(false);
}
    
    
    
    private void carregarTabelaFuncao() {

    String sql = "SELECT \"ID_FUNCAO\", \"NOME_FUNCAO\" "
            + "FROM \"Funcao\" "
            + "ORDER BY UPPER(\"NOME_FUNCAO\")";

    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"ID", "FUNÇÃO"}
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // 🔒 impede edição direta
        }
    };

    try (java.sql.Connection conn = br.com.Conexao.ConexaoPostgres.conectar();
         java.sql.PreparedStatement ps = conn.prepareStatement(sql);
         java.sql.ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("ID_FUNCAO"),
                rs.getString("NOME_FUNCAO")
            });
        }

        jTableFuncao.setModel(model);

        // 🔹 Ajuste de colunas
        jTableFuncao.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        jTableFuncao.getColumnModel().getColumn(0).setPreferredWidth(60);   // ID
        jTableFuncao.getColumnModel().getColumn(1).setPreferredWidth(410);  // FUNCAO

        // 🔹 Melhorias visuais
        jTableFuncao.getTableHeader().setReorderingAllowed(false);
        jTableFuncao.setRowHeight(18);

    } catch (Exception e) {
        e.printStackTrace();
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonNovo = new javax.swing.JRadioButton();
        jRadioEditar = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFuncao = new javax.swing.JTable();
        jTextFieldIDSetor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFuncao = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Funções");

        jRadioButtonNovo.setText("Novo");
        jRadioButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNovoActionPerformed(evt);
            }
        });

        jRadioEditar.setText("Editar");
        jRadioEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEditarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jTableFuncao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableFuncao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFuncaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFuncao);

        jLabel2.setText("Função");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonNovo)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioEditar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldIDSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldIDSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonNovo)
                    .addComponent(jRadioEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNovoActionPerformed
      // Desmarca editar
        jRadioEditar.setSelected(false);

        // Limpa os campos
        jTextFieldIDSetor.setText("");
        jTextFieldFuncao.setText("");

        // Foco no campo função
        jTextFieldFuncao.requestFocus();
    }//GEN-LAST:event_jRadioButtonNovoActionPerformed

    private void jRadioEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEditarActionPerformed
        // Desmarca novo
        jRadioButtonNovo.setSelected(false);
    }//GEN-LAST:event_jRadioEditarActionPerformed

    private void jTableFuncaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFuncaoMouseClicked
      int linha = jTableFuncao.getSelectedRow();

        if (linha != -1) {

            Object id = jTableFuncao.getValueAt(linha, 0);
            Object funcao = jTableFuncao.getValueAt(linha, 1);

            jTextFieldIDSetor.setText(id != null ? id.toString() : "");
            jTextFieldFuncao.setText(funcao != null ? funcao.toString() : "");
        } 
    }//GEN-LAST:event_jTableFuncaoMouseClicked

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
     if (!jRadioButtonNovo.isSelected() && !jRadioEditar.isSelected()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma opção antes de salvar.");
            return;
        }

        String funcao = jTextFieldFuncao.getText().trim();

        // Validação da função (obrigatória)
        if (funcao.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Informe a Função");
            jTextFieldFuncao.requestFocus();
            return;
        }

        try (java.sql.Connection conn = br.com.Conexao.ConexaoPostgres.conectar()) {

            String sql;

            // NOVO
            if (jRadioButtonNovo.isSelected()) {
                sql = "INSERT INTO \"Funcao\" (\"NOME_FUNCAO\") VALUES (?)";
            } 
            // EDITAR
            else if (jRadioEditar.isSelected()) {

                if (jTextFieldIDSetor.getText().isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Selecione um registro para editar");
                    return;
                }

                sql = "UPDATE \"Funcao\" SET \"NOME_FUNCAO\"=? WHERE \"ID_FUNCAO\"=?";
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Selecione Novo ou Editar");
                return;
            }

            try (java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {

                ps.setString(1, funcao);

                // Se for editar, seta o ID
                if (jRadioEditar.isSelected()) {
                    ps.setInt(2, Integer.parseInt(jTextFieldIDSetor.getText()));
                }

                ps.executeUpdate();

                javax.swing.JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
                
                // Limpeza e reset da tela
                jTextFieldIDSetor.setText("");
                jTextFieldFuncao.setText("");
                jRadioButtonNovo.setSelected(false);
                jRadioEditar.setSelected(false);
                carregarTabelaFuncao();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }  
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadFuncao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadFuncao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadFuncao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadFuncao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadFuncao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButtonNovo;
    private javax.swing.JRadioButton jRadioEditar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFuncao;
    private javax.swing.JTextField jTextFieldFuncao;
    private javax.swing.JTextField jTextFieldIDSetor;
    // End of variables declaration//GEN-END:variables
}
