/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.Visao;

import br.com.Utilidades.Criptografia;
import br.com.Conexao.ConexaoPostgres;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author Lavanderia
 */
public class TelaLoginNova extends javax.swing.JDialog {

    /**
     * Creates new form TelaLoginNova
     */
    public TelaLoginNova(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTextFieldUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent e) {

                jTextFieldUsuario.setText(
                        jTextFieldUsuario.getText().toUpperCase()
                );

                jTextFieldUsuario.setCaretPosition(
                        jTextFieldUsuario.getText().length()
                );

            }
        });

        setLocationRelativeTo(null);

        jTextFieldUsuario.putClientProperty(
                "JTextField.placeholderText",
                "Usuário");

        jPasswordFieldSenha.putClientProperty(
                "JTextField.placeholderText",
                "Senha");

        jTextFieldUsuario.putClientProperty(
                "JComponent.roundRect",
                true);

        jPasswordFieldSenha.putClientProperty(
                "JComponent.roundRect",
                true);

        jButtonOK.putClientProperty(
                "JButton.buttonType",
                "roundRect");

        jButtonOK.putClientProperty(
                "JButton.buttonType",
                "roundRect");

        jButtonOK.setBackground(
                new java.awt.Color(0, 120, 215));

        jButtonOK.setForeground(
                java.awt.Color.WHITE);

        jTextFieldUsuario.setPreferredSize(
                new java.awt.Dimension(280, 35));

        jPasswordFieldSenha.setPreferredSize(
                new java.awt.Dimension(280, 35));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de RH - Cofril");
        setBackground(new java.awt.Color(255, 255, 255));
        setModal(true);
        setResizable(false);

        jPanelPrincipal.setBackground(new java.awt.Color(250, 250, 250));

        jButtonOK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonOK.setText("Entrar");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jPasswordFieldSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CadeadoGrande.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RH ABAV");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CadeadoSenha.png"))); // NOI18N

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2)
                        .addGap(0, 82, Short.MAX_VALUE))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(53, 186, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPasswordFieldSenha))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed

        String usuario = jTextFieldUsuario.getText().trim();
        String senhaDigitada = new String(jPasswordFieldSenha.getPassword()).trim();

        if (usuario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite o usuário.");
            jTextFieldUsuario.requestFocus();
            return;
        }

        String senhaBanco = null;
        String nivel = null;
        boolean usuarioEncontrado = false;

        try ( Connection conn = ConexaoPostgres.conectar()) {

            /*
            ===============================
            SELECT USUÁRIO
            ===============================
             */
            try ( PreparedStatement stmt = conn.prepareStatement(
                    "SELECT \"SENHA\", \"NIVEL\" FROM \"Usuario\" WHERE \"NOME\" = ?")) {

                stmt.setString(1, usuario);

                try ( ResultSet rs = stmt.executeQuery()) {

                    if (rs.next()) {
                        usuarioEncontrado = true;
                        senhaBanco = rs.getString("SENHA");
                        nivel = rs.getString("NIVEL");
                    }

                }

            }

            if (!usuarioEncontrado) {
                JOptionPane.showMessageDialog(this, "Usuário inválido.");
                return;
            }

            /*
        ===============================
        SENHA NOVA
        ===============================
             */
            if (senhaBanco == null || senhaBanco.trim().isEmpty()) {

                if (senhaDigitada.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Digite sua nova senha");
                    jPasswordFieldSenha.requestFocus();
                    return;
                }

                try ( PreparedStatement stmtUpdate = conn.prepareStatement(
                        "UPDATE \"Usuario\" SET \"SENHA\" = ? WHERE \"NOME\" = ?")) {

                    stmtUpdate.setString(1,
                            Criptografia.criptografarSenha(senhaDigitada));

                    stmtUpdate.setString(2, usuario);

                    stmtUpdate.executeUpdate();

                    JOptionPane.showMessageDialog(this,
                            "Senha cadastrada com sucesso!");

                    abrirProximaTela(usuario, nivel);

                    return;

                }

            }

            /*
        ===============================
        VALIDAR SENHA
        ===============================
             */
            String senhaCriptografada
                    = Criptografia.criptografarSenha(senhaDigitada);

            if (senhaCriptografada.equals(senhaBanco.trim())) {

                abrirProximaTela(usuario, nivel);

            } else {

                JOptionPane.showMessageDialog(this, "Senha incorreta.");

                jPasswordFieldSenha.setText("");

                jPasswordFieldSenha.requestFocus();

            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,
                    "Erro de conexão: " + e.getMessage());

        }

    }//GEN-LAST:event_jButtonOKActionPerformed

    private void abrirProximaTela(String usuario, String nivel) {

        this.setVisible(false);

        try {

            javax.swing.UIManager.setLookAndFeel(
                    "javax.swing.plaf.nimbus.NimbusLookAndFeel"
            );

        } catch (Exception e) {

            e.printStackTrace();

        }

        TelaFuncionarios tela
                = new TelaFuncionarios(usuario, nivel);

        tela.setLocationRelativeTo(null);

        tela.setVisible(true);

        this.dispose();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        // Ativa FlatLaf somente para a TelaLoginNova
        try {

            com.formdev.flatlaf.FlatLightLaf.setup();

        } catch (Exception ex) {

            ex.printStackTrace();

        }

        // Abre a tela de login
        java.awt.EventQueue.invokeLater(() -> {

            new TelaLoginNova(null, true).setVisible(true);

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
