/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.Visao;

/**
 *
 * @author Lavanderia
 */
public class TelaCadSetor extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadSetor
     */
    public TelaCadSetor() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        carregarTabelaSetor();
        carregarEncarregados();
        jTextFieldIDSetor.setEnabled(false);
    }

    private void carregarTabelaSetor() {

        String sql = "SELECT \"ID_SETOR\", \"NOME_SETOR\", \"ENCARREGADO\" "
                + "FROM \"Setor\" "
                + "ORDER BY UPPER(\"NOME_SETOR\")";

        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"ID", "SETOR", "ENCARREGADO"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // 🔒 impede edição direta
            }
        };

        try ( java.sql.Connection conn = br.com.Conexao.ConexaoPostgres.conectar();  java.sql.PreparedStatement ps = conn.prepareStatement(sql);  java.sql.ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("ID_SETOR"),
                    rs.getString("NOME_SETOR"),
                    rs.getString("ENCARREGADO")
                });
            }

            jTableSetor.setModel(model);

            // 🔹 Ajuste de colunas
            jTableSetor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

            jTableSetor.getColumnModel().getColumn(0).setPreferredWidth(60);   // ID
            jTableSetor.getColumnModel().getColumn(1).setPreferredWidth(230);  // SETOR
            jTableSetor.getColumnModel().getColumn(2).setPreferredWidth(217);  // ENCARREGADO

            // 🔹 Melhorias visuais
            jTableSetor.getTableHeader().setReorderingAllowed(false);
            jTableSetor.setRowHeight(18);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void carregarEncarregados() {

        String sql = "SELECT \"NOME\" "
                + "FROM \"Funcionarios\" "
                + "WHERE \"FUNCAO\" ILIKE '%ENC%' "
                + "AND UPPER(\"STATUS\") = 'ATIVO' "
                + "ORDER BY \"NOME\"";

        try ( java.sql.Connection conn = br.com.Conexao.ConexaoPostgres.conectar();  java.sql.PreparedStatement ps = conn.prepareStatement(sql);  java.sql.ResultSet rs = ps.executeQuery()) {

            jComboBoxEncarregado.removeAllItems();

            // 🔹 Item padrão
            jComboBoxEncarregado.addItem("Selecione o Encarregado");

            while (rs.next()) {
                jComboBoxEncarregado.addItem(rs.getString("NOME"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jRadioButtonNovo = new javax.swing.JRadioButton();
        jRadioEditar = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSetor = new javax.swing.JTable();
        jTextFieldIDSetor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSetor = new javax.swing.JTextField();
        jComboBoxEncarregado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Casdastro de Setores");

        jLabel3.setText("Encarregado");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jRadioButtonNovo.setText("Novo");
        jRadioButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNovoActionPerformed(evt);
            }
        });

        jRadioEditar.setText("Editar");
        jRadioEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEditarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jTableSetor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSetor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSetorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSetor);

        jLabel2.setText("Setor");

        jComboBoxEncarregado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonNovo)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldIDSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jTextFieldSetor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel2)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxEncarregado, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIDSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jComboBoxEncarregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioEditar)
                        .addComponent(jRadioButtonNovo)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (!jRadioButtonNovo.isSelected() && !jRadioEditar.isSelected()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma opção antes de salvar.");
            return;
        }

        String setor = jTextFieldSetor.getText().trim();

        // validação do setor (continua obrigatória)
        if (setor.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Informe o Setor");
            jTextFieldSetor.requestFocus();
            return;
        }

        try ( java.sql.Connection conn = br.com.Conexao.ConexaoPostgres.conectar()) {

            String sql;

            // NOVO
            if (jRadioButtonNovo.isSelected()) {
                sql = "INSERT INTO \"Setor\" (\"NOME_SETOR\", \"ENCARREGADO\") VALUES (?, ?)";
            } // EDITAR
            else if (jRadioEditar.isSelected()) {

                if (jTextFieldIDSetor.getText().isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Selecione um registro para editar");
                    return;
                }

                sql = "UPDATE \"Setor\" SET \"NOME_SETOR\"=?, \"ENCARREGADO\"=? WHERE \"ID_SETOR\"=?";
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Selecione Novo ou Editar");
                return;
            }

            try ( java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {

                ps.setString(1, setor);

                // 🔥 AQUI É A VALIDAÇÃO QUE VOCÊ QUER
                if (jComboBoxEncarregado.getSelectedIndex() == 0) {
                    ps.setNull(2, java.sql.Types.VARCHAR);
                } else {
                    ps.setString(2, jComboBoxEncarregado.getSelectedItem().toString());
                }

                // se for editar, seta o ID
                if (jRadioEditar.isSelected()) {
                    ps.setInt(3, Integer.parseInt(jTextFieldIDSetor.getText()));
                }

                ps.executeUpdate();

                javax.swing.JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
                jTextFieldIDSetor.setText("");
                jTextFieldSetor.setText("");
                jComboBoxEncarregado.setSelectedItem("Selecione o Encarregado");
                jRadioButtonNovo.setSelected(false);
                jRadioEditar.setSelected(false);
                carregarTabelaSetor();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jRadioButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNovoActionPerformed
        // Desmarca editar
        jRadioEditar.setSelected(false);

        // Limpa os campos
        jTextFieldIDSetor.setText("");
        jTextFieldSetor.setText("");
        jComboBoxEncarregado.setSelectedIndex(0);

        // Foco no campo setor
        jTextFieldSetor.requestFocus();
    }//GEN-LAST:event_jRadioButtonNovoActionPerformed

    private void jRadioEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEditarActionPerformed
            jRadioButtonNovo.setSelected(false);

    }//GEN-LAST:event_jRadioEditarActionPerformed

    private void jTableSetorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSetorMouseClicked
        int linha = jTableSetor.getSelectedRow();

        if (linha != -1) {

            Object id = jTableSetor.getValueAt(linha, 0);
            Object setor = jTableSetor.getValueAt(linha, 1);
            Object encarregado = jTableSetor.getValueAt(linha, 2);

            jTextFieldIDSetor.setText(id != null ? id.toString() : "");
            jTextFieldSetor.setText(setor != null ? setor.toString() : "");
            jComboBoxEncarregado.setSelectedItem(
                    encarregado != null ? encarregado.toString() : "Selecione o Encarregado"
            );
        }

    }//GEN-LAST:event_jTableSetorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadSetor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxEncarregado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButtonNovo;
    private javax.swing.JRadioButton jRadioEditar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSetor;
    private javax.swing.JTextField jTextFieldIDSetor;
    private javax.swing.JTextField jTextFieldSetor;
    // End of variables declaration//GEN-END:variables
}
